server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          music-client-oidc:
            provider: spring
            client-id: app1
            client-secret: myClientSecretValue
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: music-client-oidc
          music-client-authorization-code:
            provider: spring
            client-id: app1
            client-secret: myClientSecretValue
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: SCOPE_music.read
            client-name: music-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000